### ISSUE TITLE
Form labels

### ISSUE THREAD

**Issue by DanGamble89** [BowlingX/flexcss#2]
Why are you using:

```
padding: 5px 1rem 0 0;
position: relative;
top: 5px;
```

Instead of just

```
align-self: center;
margin-right: 10px;
```

Just curious as it seems the whole thing is based around flex but you aren't utilising it in some places

**Comment by BowlingX** [comment]
Hey :), good Question :).

the label should not be centered relative to the controls, just be centered to the text inside the given control (e.g. an input field). `align-self:center` would not be nice looking with a `textarea` for instance (or any taller element).

**Comment by DanGamble89** [comment]
That's a fair point when it comes to textareas. Is there a reason you use `postion: relative` instead of `margin-top: 5px` in this case as well?

**Comment by BowlingX** [comment]
not that I know off right now :D. I can't remember why I did this.

**Comment by DanGamble89** [comment]
Haha fair enough well it answers the questions i had with acceptable answers so i'll close it :)
